name: cpp-linter-formatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12-dev environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12-dev'
      
      - name: Install Conan
        run: |
          python -m pip install --upgrade pipx
          pipx install conan
      
      - name: Install Poetry
        run: pipx install poetry 

      - name: Install CMake and Ninja
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build

      - name: Install dependencies via Conan
        run: |
          conan profile detect
          conan install . --build=missing

      - name: Install dependencies via Poetry
        run: poetry install

      - name: Install clang-tidy and clang-format
        run: |
          sudo apt update
          sudo apt install -y clang-tidy clang-format

      - name: Generate compile_commands.json file
        run: |
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES ..
          cd ..

      - name: Run linter and formatter checks
        run: |
          find src/cppsrc -name "*.cpp" -or -name "*.hpp" | xargs clang-tidy -p=build
          find src/cppsrc -name "*.cpp" -or -name '*.hpp' | xargs clang-format --dry-run --Werror