name: cpp-linter-formatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install --upgrade pipx
          pipx install cmake ninja conan poetry clang-tidy clang-format

      - name: Run conan profile detect
        run: |
          conan profile detect

      - name: Run linter and formatter checks
        run: |
          make lint_format_check_cpp